services:
  cache-1:
    container_name: video-streaming-cache-1
    image: caddy
    volumes:
      - ./Caddyfile-1:/etc/caddy/Caddyfile
      - ./certs:/root/certs
      - ../dataset:/srv
    environment:
      latitude: "some_value1"
      longitude: "another_value1"
      
  cache-2:
    container_name: video-streaming-cache-2
    image: caddy
    volumes:
      - ./Caddyfile-2:/etc/caddy/Caddyfile
      - ./certs:/root/certs
      - ../dataset:/srv
    environment:
      latitude: "some_value2"
      longitude: "another_value2"
      
  cache-3:
    container_name: video-streaming-cache-3
    image: caddy
    volumes:
      - ./Caddyfile-3:/etc/caddy/Caddyfile
      - ./certs:/root/certs
      - ../dataset:/srv
    environment:
      latitude: "some_value3"
      longitude: "another_value3"
      