name: video-streaming

services:
  caddy:
    image: caddy
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/root/certs
      - ../dataset:/srv
      
