services:
  cache-1:
    container_name: video-streaming-cache-1
    image: caddy
    volumes:
      - ./Caddyfile-1:/etc/caddy/Caddyfile
      - ./certs:/root/certs
      - ../dataset:/srv
    environment:
      LATITUDE: "-23"
      LONGITUDE: "-47"
      
  cache-2:
    container_name: video-streaming-cache-2
    image: caddy
    volumes:
      - ./Caddyfile-2:/etc/caddy/Caddyfile
      - ./certs:/root/certs
      - ../dataset:/srv
    environment:
      LATITUDE: "-33"
      LONGITUDE: "-71"
      
  cache-3:
    container_name: video-streaming-cache-3
    image: caddy
    volumes:
      - ./Caddyfile-3:/etc/caddy/Caddyfile
      - ./certs:/root/certs
      - ../dataset:/srv
    environment:
      LATITUDE: "5"
      LONGITUDE: "-74"
      